# Configuración básica del proyecto
name = "cyberpunk-landing"
compatibility_date = "2025-08-11"

# Configuración específica para Pages
[pages]
build_output_directory = "out"

# Configuración del proceso de build
[build]
command = "pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "20"
