name = "cyberpunk"
account_id = "acb74b82adc41de67cb013adee07f38f"

[pages]
build_output_directory = "out"

[build]
command = "pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "20"
